#!/bin/bash
#Amazon Linux 2
# Update system packages
sudo yum update -y
sudo yum install -y tar wget
cd /opt
sudo wget https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz
sudo tar -xzvf jdk-21_linux-x64_bin.tar.gz
sudo rm -f jdk-21_linux-x64_bin.tar.gz
sudo ln -sf /opt/jdk-21*/bin/java /usr/bin/java
echo 'export JAVA_HOME=/opt/jdk-21' | sudo tee /etc/profile.d/java.sh
echo 'export PATH=$JAVA_HOME/bin:$PATH' | sudo tee -a /etc/profile.d/java.sh
source /etc/profile.d/java.sh
